export default defineEventHandler(async () => {
  const db = useDatabase()
  await db.prepare('BEGIN').run()
  await db.prepare('DROP TABLE IF EXISTS users').run()
  await db.prepare('DROP TABLE IF EXISTS sessions').run()
  await db.prepare('DROP TABLE IF EXISTS emailVerifications').run()
  await db.prepare('CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NULLABLE, googleId TEXT NULLABLE, appleId TEXT NULLABLE, githubId TEXT NULLABLE, microsoftId TEXT NULLABLE)').run()
  await db.prepare('CREATE TABLE sessions (sessionId TEXT PRIMARY KEY, userId TEXT NOT NULL, clientId TEXT NOT NULL, tokenHash TEXT NOT NULL)').run()
  await db.prepare('CREATE TABLE emailVerifications (email TEXT NOT NULL, verificationCode TEXT NULLABLE, authorizationCode TEXT NULLABLE, verificationCodeExpiration INTEGER NULLABLE, authorizationCodeExpiration INTEGER NULLABLE)').run()
  await db.prepare('COMMIT').run()
  return noError()
})
